### ISSUE TITLE
Error with aft_customizations_identify_targets (Exception:  Item)

### ISSUE THREAD

**Issue by Menahem1** [aws-ia/terraform-aws-control_tower_account_factory#237]
**AFT Version:** 1.6.2

**Bug Description**
Hello,
When i try to launch the step functions "aft-invoke-customizations" with all account's (sixty) i encounter a fail

**To Reproduce**
1. Go to step functions -> "aft-invoke-customizations"
2. Try an execution in all accounts 
```
 {
  "include": [
    {
      "type": "all"
    }
  ]
}
```
4. Wait a few seconds, and it's failing 

**Expected behavior**
Ability to invoke a customizations in all account's managed by AFT

**Related Logs**

```
{
    "time_stamp": "2022-09-08 15:18:23,385",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_customizations_identify_targets.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": "'Item'"
    }
}
Traceback (most recent call last):
  File "/var/task/aft_customizations_identify_targets.py", line 62, in lambda_handler
    build_customization_invoke_event_for_target_account(
  File "/opt/python/lib/python3.8/site-packages/aft_common/customizations.py", line 324, in build_customization_invoke_event_for_target_account
    account_request_record = get_account_request_record(
  File "/opt/python/lib/python3.8/site-packages/aft_common/customizations.py", line 290, in get_account_request_record
    item: Dict[str, Any] = response["Item"]
KeyError: 'Item'
```

**Comment by stumins** [comment]
Hi @Menahem1,

I believe this is a duplicate of https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/176 - please see this issue for the root cause & workarounds.

There is an item in the backlog to fix this bug.

**Comment by stumins** [comment]
I'll go ahead and close this issue as a duplicate - however, please feel free to provide additional details if you feel like this is not a duplicate and we can re-open this issue.
