### ISSUE TITLE
aft-invoke-aft-account-provisioning-framework failing with InvalidInputException

### ISSUE THREAD

**Issue by joowani** [aws-ia/terraform-aws-control_tower_account_factory#287]
**Terraform Version & Prov:**

**AFT Version:**
1.6.7

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
0.15.5
```

`terraform providers`
```
hashicorp/aws v4.48.0
```

**Bug Description**
New AWS account provisioning via AFT fails at Lambda `/aws/lambda/aft-invoke-aft-account-provisioning-framework`. See below for stacktrace.

**To Reproduce**
1. Define a new account in my `terraform-aft-account-request` Github repository and push

**Expected behavior**
The new account should be created.

**Related Logs**

Example Request ID: 751dd8ee-dc1c-4bdb-a2a2-e9d20e691c1c

```
{
    "time_stamp": "2022-12-23 23:30:25,800",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_invoke_aft_account_provisioning_framework.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": "An error occurred (InvalidInputException) when calling the DescribeAccount operation: You provided a value that does not match the required pattern."
    }
}
Traceback (most recent call last):
  File "/var/task/aft_invoke_aft_account_provisioning_framework.py", line 39, in lambda_handler
    invoke_event = build_invoke_event(
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py", line 420, in build_invoke_event
    account_email = utils.get_account_email_from_id(
  File "/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py", line 391, in get_account_email_from_id
    response: DescribeAccountResponseTypeDef = orgs.describe_account(AccountId=id)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidInputException: An error occurred (InvalidInputException) when calling the DescribeAccount operation: You provided a value that does not match the required pattern.
```

**Comment by balltrev** [comment]
Hey @joowani, thanks for reaching out. The Account ID used in the `orgs.describe_account` call should be present in an event emitted by AWS Control Tower. We've recently touched on the Organizations logic in AFT, I would recommend that you upgrade to the latest release and re-attempt the account request process, or reach out to AWS Premium support to help better understand why the event may not have had an Account ID.

**Comment by stumins** [comment]
Closing due to inactivity - please open a new ticket if you experience this issue on 1.7.0+
