### ISSUE TITLE
Onboarding shared CT accounts doesn't work with control tower accepted OU format

### ISSUE THREAD

**Issue by Flydiverny** [aws-ia/terraform-aws-control_tower_account_factory#322]
**AFT Version:**
1.9.1

**Terraform Version & Provider Versions**
N/A

**Bug Description**

**To Reproduce**
1.  Add Account Request for a Shared account (like Audit or Log Archive)
2. In your Account Request specify the OU as `Security (ou-<id>)`
3. Commit and Push it so the AFT pipelines run!

**Expected behavior**
Expect successful AFT import of existing shared account.

**Related Logs**

in `/aws/lambda/aft-account-request-action-trigger`

```
[ERROR] ValueError: Unsupported action: Cannot change OU for a Shared CT account or CT management account
Traceback (most recent call last):
  File "/var/task/aft_account_request_action_trigger.py", line 42, in lambda_handler
    ) and shared_account_request(event_record=record_handler.record):
  File "/opt/python/lib/python3.8/site-packages/aft_common/shared_account.py", line 48, in shared_account_request
    raise ValueError(
```

**Additional context**
Changing the OU in the account request to just `ou-<id>` seems to do the trick.
In our account requests we always specify the long version in the OU field as its required in some circumstances by control tower and seems to work in all cases. In the case of onboarding shared accounts I can see AFT takes another code path and so its trying to parse this OU by itself.

Ref https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/320#issuecomment-1457072568

**Comment by adam-daily** [comment]
Hey Markus, appreciate you reaching out. I've added these details to our backlog, thanks for identifying this inconsistency.

**Comment by Chainshark** [comment]
> Duplicate of #206

@balltrev That issue is over a year old.. How can an organisation expect to use AFT if blocking issues aren't solved after such a long time?

I wanted to use the AFT Account Request repo to deploy certain roles and resources into all accounts, but if I can't import my audit/log archive account, that's a huge upset.

**Comment by umegaya** [comment]
@brhankel In my case, I have multiple nested OUs with the same name, so I need to specify the OU-ID. there is any workaround for the situation?
