### ISSUE TITLE
AFT Account Creation Failure and Troubleshooting

### ISSUE THREAD

**Issue by jeremyciak** [aws-ia/terraform-aws-control_tower_account_factory#61]
I have deployed AFT and set up the repositories. I then committed an account request, which successfully resulted in the pipeline running and submitting an entry to DynamoDB. However, it seems like the rest of the automation has failed somewhere and I'm not really sure how best to troubleshoot. I went to CloudWatch and looked at logs and it seems like the `aft-account-request-processor` Lambda is claiming to not find messages in the `aft-account-request.fifo` queue. I investigated that and found that the message had made its way into the `aft-account-request-dlq.fifo` dead-letter queue.

I'm not really sure where to go from there. The next thing I tried was to resubmit a message to the `aft-account-request.fifo` queue with the same body as the first message, then triggered the `aft-account-request-processor` Lambda to run again. The message ended up in the dead-letter queue again and the CloudWatch logs reported no messages found again. Please help!

**Comment by rcuenotag** [comment]
Just hit this issue with whitespace as well. AFT should support whitespace, as the default Log Archive account created with Control Tower contains whitespace. I assume the regex pattern will need to be updated within aft_account_request_action_trigger.py

```
{
    "time_stamp": "2022-02-14 22:45:05,505",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_account_request_action_trigger.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": "An error occurred (ValidationException) when calling the DescribeProvisionedProduct operation: 1 validation error detected: Value 'Robby Sandbox' at 'name' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9][a-zA-Z0-9._-]*"
    }
}
Traceback (most recent call last):
  File "/var/task/aft_account_request_action_trigger.py", line 44, in lambda_handler
    new_account = not provisioned_product_exists(event_record)
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py", line 37, in provisioned_product_exists
    provisioned_product = Account(
  File "/opt/python/lib/python3.8/site-packages/aft_common/account.py", line 35, in provisioned_product
    client.describe_provisioned_product(Name=self.account_name)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the DescribeProvisionedProduct operation: 1 validation error detected: Value 'Robby Sandbox' at 'name' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9][a-zA-Z0-9._-]*
```

This is within the aft-account-request-action-trigger Lambda function.

**Comment by balltrev** [comment]
This is actually a limitation of Service Catalog and their provisioned product names not supporting spaces if I understand correctly. We've got a backlog to remove this limitation, but for now the account name as you've run into, doesn't support spaces within the name.
